# -*- coding: utf-8 -*-
"""Web Scraping-News APi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KPZBtp_nYLFfDYN4qoZFlBWTmPuSFeKQ

# **Dataset Berita Kesehatan di Indonesia Tahun 2023**
"""
# import library
! pip install requests

import requests
import pprint
import json
import pandas as pd

# describe api key 
api_key="your api key"

# parameter request for news result 
city = 'Indonesia'
query = f'{city}'
main_url=f"https://newsapi.org/v2/top-headlines?country=id&category=health"

parameters = {
    'q': 'health', # keyword 
    'pageSize': 100, # count of result
    'apiKey': api_key, 
    'country': 'id',
    'from': '2023-08-24',
    'to': '2023-09-24',
}

response = requests.get(main_url, params=parameters) # request get
response_json = response.json()
print(response_json.keys())

news = response_json['articles']
print(news)

data = []
for i in response_json['articles']:
  article = {
      'title': (i['title']),
      'author': (i['author']),
      'url': (i['url']),
      'description': (i['description']),
      'publishedAt': (i['publishedAt'])
  }
  data.append(article)

# make result into dataframe
df = pd.DataFrame(data)
df

# make dataframe into csv
df.to_csv('news.csv')

